import {
  UserDTO,
  WarehouseDTO,
  CategoryDTO,
  SupplierDTO,
  CustomerDTO,
  ProductDTO,
  InventoryTransactionDTO,
  PurchaseOrderDTO,
  SalesOrderDTO,
  StockTransferDTO,
  LowStockAlertDTO,
  NotificationDTO,
  ForecastDTO,
  AuditLogDTO,
} from "@/types";

export const INITIAL_USERS: UserDTO[] = [
  {
    id: "usr-admin-1",
    name: "Alexander Vance",
    email: "admin@smartinventory.io",
    role: "ADMIN",
    phone: "+1 (555) 019-2834",
    status: "ACTIVE",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    createdAt: "2026-01-15T08:00:00Z",
  },
  {
    id: "usr-wm-1",
    name: "Elena Rostova",
    email: "warehouse@smartinventory.io",
    role: "WAREHOUSE_MANAGER",
    phone: "+1 (555) 018-9123",
    status: "ACTIVE",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    createdAt: "2026-01-16T09:30:00Z",
  },
  {
    id: "usr-sm-1",
    name: "Marcus Sterling",
    email: "sales@smartinventory.io",
    role: "SALES_MANAGER",
    phone: "+1 (555) 017-4567",
    status: "ACTIVE",
    warehouseId: "wh-2",
    warehouseName: "North Branch Store",
    createdAt: "2026-01-20T10:15:00Z",
  },
  {
    id: "usr-staff-1",
    name: "Sophia Chen",
    email: "staff@smartinventory.io",
    role: "STAFF",
    phone: "+1 (555) 014-7890",
    status: "ACTIVE",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    createdAt: "2026-02-01T11:00:00Z",
  },
];

export const INITIAL_WAREHOUSES: WarehouseDTO[] = [
  {
    id: "wh-1",
    name: "Main Warehouse",
    code: "WH-MAIN-01",
    address: "742 Evergreen Logistics Blvd",
    city: "Chicago",
    country: "USA",
    phone: "+1 (312) 555-0100",
    email: "chicago@smartinventory.io",
    managerName: "Elena Rostova",
    status: "ACTIVE",
    totalProductsCount: 12,
    totalInventoryValue: 284500.0,
    lowStockItemsCount: 2,
    createdAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "wh-2",
    name: "North Branch Store",
    code: "WH-EAST-02",
    address: "100 Portway Terminal Rd",
    city: "Newark",
    country: "USA",
    phone: "+1 (201) 555-0200",
    email: "newark@smartinventory.io",
    managerName: "David Kross",
    status: "ACTIVE",
    totalProductsCount: 10,
    totalInventoryValue: 142300.0,
    lowStockItemsCount: 1,
    createdAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "wh-3",
    name: "South Branch Store",
    code: "WH-WEST-03",
    address: "888 Pacific Gateway Parkway",
    city: "Oakland",
    country: "USA",
    phone: "+1 (510) 555-0300",
    email: "oakland@smartinventory.io",
    managerName: "Sarah Jenkins",
    status: "ACTIVE",
    totalProductsCount: 8,
    totalInventoryValue: 98400.0,
    lowStockItemsCount: 0,
    createdAt: "2026-02-01T00:00:00Z",
  },
  {
    id: "wh-4",
    name: "Overflow Storage",
    code: "WH-EU-04",
    address: "Hafenstrasse 45",
    city: "Hamburg",
    country: "Germany",
    phone: "+49 40 555 0400",
    email: "hamburg@smartinventory.io",
    managerName: "Hans Weber",
    status: "ACTIVE",
    totalProductsCount: 6,
    totalInventoryValue: 76000.0,
    lowStockItemsCount: 1,
    createdAt: "2026-02-15T00:00:00Z",
  },
];

export const INITIAL_CATEGORIES: CategoryDTO[] = [
  { id: "cat-1", name: "Electronics", slug: "industrial-electronics", description: "Laptops, phones, tablets, monitors & accessories", productCount: 4 },
  { id: "cat-2", name: "Office Supplies", slug: "power-tools", description: "Pens, paper, folders, stationery & printer supplies", productCount: 3 },
  { id: "cat-3", name: "Clothing & Apparel", slug: "ppe-safety", description: "T-shirts, pants, shoes, bags & accessories", productCount: 3 },
  { id: "cat-4", name: "Food & Beverages", slug: "packaging-logistics", description: "Drinks, snacks, canned goods & dry food items", productCount: 2 },
];

export const INITIAL_SUPPLIERS: SupplierDTO[] = [
  {
    id: "sup-1",
    name: "TechPro Distribution Co.",
    contactPerson: "Robert Sterling",
    email: "orders@apexprecision.com",
    phone: "+1 (800) 555-4010",
    address: "450 Silicon Expressway",
    city: "Austin",
    country: "USA",
    status: "ACTIVE",
    notes: "Primary supplier for laptops, monitors and computer accessories.",
    totalPurchased: 145000.0,
    purchaseOrdersCount: 8,
    createdAt: "2026-01-05T00:00:00Z",
  },
  {
    id: "sup-2",
    name: "Office World Supplies",
    contactPerson: "Clara Vance",
    email: "sales@vanguardtools.com",
    phone: "+1 (800) 555-4020",
    address: "1200 Heavy Foundry Way",
    city: "Cleveland",
    country: "USA",
    status: "ACTIVE",
    notes: "Preferred supplier for office stationery, paper and printer supplies.",
    totalPurchased: 89000.0,
    purchaseOrdersCount: 5,
    createdAt: "2026-01-12T00:00:00Z",
  },
  {
    id: "sup-3",
    name: "Bright Star Trading",
    contactPerson: "Michael O'Connor",
    email: "support@safeguardgear.com",
    phone: "+1 (800) 555-4030",
    address: "88 Armor Blvd",
    city: "Boston",
    country: "USA",
    status: "ACTIVE",
    notes: "Supplier for clothing, apparel, bags and everyday goods.",
    totalPurchased: 34200.0,
    purchaseOrdersCount: 4,
    createdAt: "2026-01-18T00:00:00Z",
  },
];

export const INITIAL_CUSTOMERS: CustomerDTO[] = [
  {
    id: "cust-1",
    name: "Star Electronics Shop",
    contactPerson: "Jessica Miller",
    email: "procurement@titanautomation.com",
    phone: "+1 (415) 555-8811",
    address: "900 Tech Plaza",
    city: "San Francisco",
    country: "USA",
    status: "ACTIVE",
    notes: "Regular retail customer, bulk electronics buyer.",
    totalSpent: 182400.0,
    salesOrdersCount: 12,
    createdAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "cust-2",
    name: "Green Valley Market",
    contactPerson: "Arthur Dent",
    email: "buyer@nexisrenewable.com",
    phone: "+1 (303) 555-8822",
    address: "500 Solar Way",
    city: "Denver",
    country: "USA",
    status: "ACTIVE",
    notes: "Grocery and market chain, orders food and beverage items weekly.",
    totalSpent: 94500.0,
    salesOrdersCount: 6,
    createdAt: "2026-01-22T00:00:00Z",
  },
  {
    id: "cust-3",
    name: "City Office Solutions",
    contactPerson: "Daniel Craig",
    email: "orders@omnibuild.com",
    phone: "+1 (214) 555-8833",
    address: "3100 Steel Frame Ave",
    city: "Dallas",
    country: "USA",
    status: "ACTIVE",
    notes: "Office furniture and supplies company, orders chairs and stationery in bulk.",
    totalSpent: 67800.0,
    salesOrdersCount: 8,
    createdAt: "2026-02-05T00:00:00Z",
  },
];

export const INITIAL_PRODUCTS: ProductDTO[] = [
  {
    id: "prod-1",
    name: "Dell Laptop 15-inch",
    sku: "DELL-LAPTOP-001",
    barcode: "890123456701",
    qrCode: "PROD:DELL-LAPTOP-001:890123456701",
    description: "15.6-inch FHD display, Intel Core i7, 16GB RAM, 512GB SSD, Windows 11 Pro.",
    uom: "unit",
    costPrice: 185.0,
    sellingPrice: 349.0,
    minStockLevel: 25,
    maxStockLevel: 200,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=500&auto=format&fit=crop&q=60",
    status: "ACTIVE",
    categoryId: "cat-1",
    categoryName: "Electronics",
    supplierId: "sup-1",
    supplierName: "TechPro Distribution Co.",
    totalStock: 140,
    totalReserved: 15,
    totalAvailable: 125,
    createdAt: "2026-01-10T00:00:00Z",
    inventories: [
      { id: "pi-1", productId: "prod-1", warehouseId: "wh-1", warehouseName: "Main Warehouse", warehouseCode: "WH-MAIN-01", quantity: 80, reservedQuantity: 10, availableQuantity: 70, locationBin: "Aisle A-03-B2", updatedAt: "2026-03-01T12:00:00Z" },
      { id: "pi-2", productId: "prod-1", warehouseId: "wh-2", warehouseName: "North Branch Store", warehouseCode: "WH-EAST-02", quantity: 45, reservedQuantity: 5, availableQuantity: 40, locationBin: "Aisle B-01-A1", updatedAt: "2026-03-01T12:00:00Z" },
      { id: "pi-3", productId: "prod-1", warehouseId: "wh-3", warehouseName: "South Branch Store", warehouseCode: "WH-WEST-03", quantity: 15, reservedQuantity: 0, availableQuantity: 15, locationBin: "Rack 4-02", updatedAt: "2026-03-01T12:00:00Z" },
    ],
  },
  {
    id: "prod-2",
    name: "Logitech Wireless Mouse",
    sku: "LOG-MOUSE-001",
    barcode: "890123456702",
    qrCode: "PROD:LOG-MOUSE-001:890123456702",
    description: "Ergonomic wireless mouse, 2.4GHz & Bluetooth, 4000 DPI, 70-day battery life.",
    uom: "unit",
    costPrice: 42.0,
    sellingPrice: 89.0,
    minStockLevel: 40,
    maxStockLevel: 300,
    imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=60",
    status: "ACTIVE",
    categoryId: "cat-1",
    categoryName: "Electronics",
    supplierId: "sup-1",
    supplierName: "TechPro Distribution Co.",
    totalStock: 35, // Below min stock (40) -> LOW STOCK
    totalReserved: 5,
    totalAvailable: 30,
    createdAt: "2026-01-12T00:00:00Z",
    inventories: [
      { id: "pi-4", productId: "prod-2", warehouseId: "wh-1", warehouseName: "Main Warehouse", warehouseCode: "WH-MAIN-01", quantity: 20, reservedQuantity: 5, availableQuantity: 15, locationBin: "Aisle A-04-C1", updatedAt: "2026-03-02T10:00:00Z" },
      { id: "pi-5", productId: "prod-2", warehouseId: "wh-2", warehouseName: "North Branch Store", warehouseCode: "WH-EAST-02", quantity: 15, reservedQuantity: 0, availableQuantity: 15, locationBin: "Aisle B-02-C3", updatedAt: "2026-03-02T10:00:00Z" },
    ],
  },
  {
    id: "prod-3",
    name: "Mechanical Keyboard TKL",
    sku: "KB-MECH-001",
    barcode: "890123456703",
    qrCode: "PROD:KB-MECH-001:890123456703",
    description: "Tenkeyless layout, hot-swap switches, RGB backlight, USB-C, compatible with Windows & Mac.",
    uom: "kit",
    costPrice: 85.0,
    sellingPrice: 179.0,
    minStockLevel: 30,
    maxStockLevel: 150,
    imageUrl: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500&auto=format&fit=crop&q=60",
    status: "ACTIVE",
    categoryId: "cat-2",
    categoryName: "Office Supplies",
    supplierId: "sup-2",
    supplierName: "Office World Supplies",
    totalStock: 95,
    totalReserved: 12,
    totalAvailable: 83,
    createdAt: "2026-01-15T00:00:00Z",
    inventories: [
      { id: "pi-6", productId: "prod-3", warehouseId: "wh-1", warehouseName: "Main Warehouse", warehouseCode: "WH-MAIN-01", quantity: 50, reservedQuantity: 8, availableQuantity: 42, locationBin: "Aisle C-01-A1", updatedAt: "2026-03-03T14:00:00Z" },
      { id: "pi-7", productId: "prod-3", warehouseId: "wh-2", warehouseName: "North Branch Store", warehouseCode: "WH-EAST-02", quantity: 30, reservedQuantity: 4, availableQuantity: 26, locationBin: "Aisle C-03-B2", updatedAt: "2026-03-03T14:00:00Z" },
      { id: "pi-8", productId: "prod-3", warehouseId: "wh-3", warehouseName: "South Branch Store", warehouseCode: "WH-WEST-03", quantity: 15, reservedQuantity: 0, availableQuantity: 15, locationBin: "Aisle C-01-D1", updatedAt: "2026-03-03T14:00:00Z" },
    ],
  },
  {
    id: "prod-4",
    name: "Ergonomic Office Chair",
    sku: "CHAIR-ERG-001",
    barcode: "890123456704",
    qrCode: "PROD:CHAIR-ERG-001:890123456704",
    description: "Mesh back, adjustable lumbar support, armrests & seat height, 150kg capacity, 5-year warranty.",
    uom: "pcs",
    costPrice: 22.0,
    sellingPrice: 48.0,
    minStockLevel: 50,
    maxStockLevel: 500,
    imageUrl: "https://images.unsplash.com/photo-1578873375969-d60fa62c57fa?w=500&auto=format&fit=crop&q=60",
    status: "ACTIVE",
    categoryId: "cat-3",
    categoryName: "Clothing & Apparel",
    supplierId: "sup-3",
    supplierName: "Bright Star Trading",
    totalStock: 240,
    totalReserved: 20,
    totalAvailable: 220,
    createdAt: "2026-01-20T00:00:00Z",
    inventories: [
      { id: "pi-9", productId: "prod-4", warehouseId: "wh-1", warehouseName: "Main Warehouse", warehouseCode: "WH-MAIN-01", quantity: 120, reservedQuantity: 10, availableQuantity: 110, locationBin: "Aisle D-01-A1", updatedAt: "2026-03-02T16:00:00Z" },
      { id: "pi-10", productId: "prod-4", warehouseId: "wh-2", warehouseName: "North Branch Store", warehouseCode: "WH-EAST-02", quantity: 70, reservedQuantity: 10, availableQuantity: 60, locationBin: "Aisle D-02-B1", updatedAt: "2026-03-02T16:00:00Z" },
      { id: "pi-11", productId: "prod-4", warehouseId: "wh-4", warehouseName: "Overflow Storage", warehouseCode: "WH-EU-04", quantity: 50, reservedQuantity: 0, availableQuantity: 50, locationBin: "Aisle E-01-A1", updatedAt: "2026-03-02T16:00:00Z" },
    ],
  },
  {
    id: "prod-5",
    name: "A4 Printer Paper 500 Sheets",
    sku: "PAPER-A4-001",
    barcode: "890123456705",
    qrCode: "PROD:PAPER-A4-001:890123456705",
    description: "80gsm white A4 paper, 500 sheets per ream, acid-free, suitable for laser & inkjet printers.",
    uom: "roll",
    costPrice: 6.5,
    sellingPrice: 15.0,
    minStockLevel: 100,
    maxStockLevel: 1000,
    imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500&auto=format&fit=crop&q=60",
    status: "ACTIVE",
    categoryId: "cat-4",
    categoryName: "Food & Beverages",
    supplierId: "sup-3",
    supplierName: "Bright Star Trading",
    totalStock: 0, // OUT OF STOCK
    totalReserved: 0,
    totalAvailable: 0,
    createdAt: "2026-01-25T00:00:00Z",
    inventories: [
      { id: "pi-12", productId: "prod-5", warehouseId: "wh-1", warehouseName: "Main Warehouse", warehouseCode: "WH-MAIN-01", quantity: 0, reservedQuantity: 0, availableQuantity: 0, locationBin: "Aisle F-01-A1", updatedAt: "2026-03-03T09:00:00Z" },
      { id: "pi-13", productId: "prod-5", warehouseId: "wh-2", warehouseName: "North Branch Store", warehouseCode: "WH-EAST-02", quantity: 0, reservedQuantity: 0, availableQuantity: 0, locationBin: "Aisle F-02-B1", updatedAt: "2026-03-03T09:00:00Z" },
    ],
  },
];

export const INITIAL_TRANSACTIONS: InventoryTransactionDTO[] = [
  {
    id: "txn-1",
    transactionNumber: "TXN-20260301-1001",
    productId: "prod-1",
    productName: "Dell Laptop 15-inch",
    productSku: "DELL-LAPTOP-001",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    quantityBefore: 30,
    quantityChange: 50,
    quantityAfter: 80,
    type: "PURCHASE_RECEIVE",
    referenceId: "po-1",
    referenceType: "PURCHASE_ORDER",
    userId: "usr-wm-1",
    userName: "Elena Rostova",
    notes: "Received batch from PO-20260228-4910",
    createdAt: "2026-03-01T10:15:00Z",
  },
  {
    id: "txn-2",
    transactionNumber: "TXN-20260301-1002",
    productId: "prod-3",
    productName: "Mechanical Keyboard TKL",
    productSku: "KB-MECH-001",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    quantityBefore: 60,
    quantityChange: -10,
    quantityAfter: 50,
    type: "SALE",
    referenceId: "so-1",
    referenceType: "SALES_ORDER",
    userId: "usr-sm-1",
    userName: "Marcus Sterling",
    notes: "Fulfillment for Star Electronics Shop SO-20260301-8841",
    createdAt: "2026-03-01T14:30:00Z",
  },
  {
    id: "txn-3",
    transactionNumber: "TXN-20260302-1003",
    productId: "prod-4",
    productName: "Ergonomic Office Chair",
    productSku: "CHAIR-ERG-001",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    quantityBefore: 140,
    quantityChange: -20,
    quantityAfter: 120,
    type: "TRANSFER_OUT",
    referenceId: "trf-1",
    referenceType: "STOCK_TRANSFER",
    userId: "usr-wm-1",
    userName: "Elena Rostova",
    notes: "Dispatched transfer to Overflow Storage",
    createdAt: "2026-03-02T11:00:00Z",
  },
  {
    id: "txn-4",
    transactionNumber: "TXN-20260302-1004",
    productId: "prod-2",
    productName: "Logitech Wireless Mouse",
    productSku: "LOG-MOUSE-001",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    quantityBefore: 22,
    quantityChange: -2,
    quantityAfter: 20,
    type: "ADJUSTMENT_DECREASE",
    referenceId: null,
    referenceType: "MANUAL_ADJUSTMENT",
    userId: "usr-wm-1",
    userName: "Elena Rostova",
    notes: "Damaged in transit during shelf relocation",
    createdAt: "2026-03-02T15:20:00Z",
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrderDTO[] = [
  {
    id: "po-1",
    orderNumber: "PO-20260228-4910",
    supplierId: "sup-1",
    supplierName: "TechPro Distribution Co.",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    orderDate: "2026-02-28T09:00:00Z",
    expectedDeliveryDate: "2026-03-05T00:00:00Z",
    status: "RECEIVED",
    totalAmount: 9250.0,
    notes: "Q1 laptop restocking batch.",
    createdById: "usr-wm-1",
    createdByName: "Elena Rostova",
    createdAt: "2026-02-28T09:00:00Z",
    items: [
      {
        id: "poi-1",
        purchaseOrderId: "po-1",
        productId: "prod-1",
        productName: "Dell Laptop 15-inch",
        productSku: "DELL-LAPTOP-001",
        quantity: 50,
        receivedQuantity: 50,
        unitCost: 185.0,
        totalCost: 9250.0,
      },
    ],
  },
  {
    id: "po-2",
    orderNumber: "PO-20260302-5102",
    supplierId: "sup-1",
    supplierName: "TechPro Distribution Co.",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    orderDate: "2026-03-02T10:00:00Z",
    expectedDeliveryDate: "2026-03-10T00:00:00Z",
    status: "SUBMITTED",
    totalAmount: 4200.0,
    notes: "Urgent restocking for wireless mouse units.",
    createdById: "usr-wm-1",
    createdByName: "Elena Rostova",
    createdAt: "2026-03-02T10:00:00Z",
    items: [
      {
        id: "poi-2",
        purchaseOrderId: "po-2",
        productId: "prod-2",
        productName: "Logitech Wireless Mouse",
        productSku: "LOG-MOUSE-001",
        quantity: 100,
        receivedQuantity: 0,
        unitCost: 42.0,
        totalCost: 4200.0,
      },
    ],
  },
  {
    id: "po-3",
    orderNumber: "PO-20260303-6021",
    supplierId: "sup-3",
    supplierName: "Bright Star Trading",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    orderDate: "2026-03-03T11:30:00Z",
    expectedDeliveryDate: "2026-03-08T00:00:00Z",
    status: "PARTIALLY_RECEIVED",
    totalAmount: 3250.0,
    notes: "Printer paper restock. 200 reams arrived first.",
    createdById: "usr-admin-1",
    createdByName: "Alexander Vance",
    createdAt: "2026-03-03T11:30:00Z",
    items: [
      {
        id: "poi-3",
        purchaseOrderId: "po-3",
        productId: "prod-5",
        productName: "A4 Printer Paper 500 Sheets",
        productSku: "PAPER-A4-001",
        quantity: 500,
        receivedQuantity: 200,
        unitCost: 6.5,
        totalCost: 3250.0,
      },
    ],
  },
];

export const INITIAL_SALES_ORDERS: SalesOrderDTO[] = [
  {
    id: "so-1",
    orderNumber: "SO-20260301-8841",
    customerId: "cust-1",
    customerName: "Star Electronics Shop",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    orderDate: "2026-03-01T13:00:00Z",
    deliveryDate: "2026-03-04T00:00:00Z",
    status: "COMPLETED",
    subtotal: 5280.0,
    discount: 100.0,
    tax: 362.6,
    totalAmount: 5542.6,
    notes: "Delivered to customer warehouse.",
    createdById: "usr-sm-1",
    createdByName: "Marcus Sterling",
    createdAt: "2026-03-01T13:00:00Z",
    items: [
      {
        id: "soi-1",
        salesOrderId: "so-1",
        productId: "prod-1",
        productName: "Dell Laptop 15-inch",
        productSku: "DELL-LAPTOP-001",
        quantity: 10,
        unitPrice: 349.0,
        totalAmount: 3490.0,
      },
      {
        id: "soi-2",
        salesOrderId: "so-1",
        productId: "prod-3",
        productName: "Mechanical Keyboard TKL",
        productSku: "KB-MECH-001",
        quantity: 10,
        unitPrice: 179.0,
        totalAmount: 1790.0,
      },
    ],
  },
  {
    id: "so-2",
    orderNumber: "SO-20260302-9112",
    customerId: "cust-2",
    customerName: "Green Valley Market",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    orderDate: "2026-03-02T15:45:00Z",
    deliveryDate: "2026-03-07T00:00:00Z",
    status: "CONFIRMED",
    subtotal: 3490.0,
    discount: 0.0,
    tax: 244.3,
    totalAmount: 3734.3,
    notes: "Awaiting packing and dispatch.",
    createdById: "usr-sm-1",
    createdByName: "Marcus Sterling",
    createdAt: "2026-03-02T15:45:00Z",
    items: [
      {
        id: "soi-3",
        salesOrderId: "so-2",
        productId: "prod-1",
        productName: "Dell Laptop 15-inch",
        productSku: "DELL-LAPTOP-001",
        quantity: 10,
        unitPrice: 349.0,
        totalAmount: 3490.0,
      },
    ],
  },
];

export const INITIAL_TRANSFERS: StockTransferDTO[] = [
  {
    id: "trf-1",
    transferNumber: "TRF-20260302-0044",
    sourceWarehouseId: "wh-1",
    sourceWarehouseName: "Main Warehouse",
    destinationWarehouseId: "wh-4",
    destinationWarehouseName: "Overflow Storage",
    status: "IN_TRANSIT",
    requestedById: "usr-admin-1",
    requestedByName: "Alexander Vance",
    sentById: "usr-wm-1",
    sentByName: "Elena Rostova",
    receivedById: null,
    receivedByName: null,
    sentDate: "2026-03-02T11:00:00Z",
    receivedDate: null,
    notes: "Transfer to overflow storage for seasonal stock",
    createdAt: "2026-03-02T10:00:00Z",
    items: [
      {
        id: "ti-1",
        stockTransferId: "trf-1",
        productId: "prod-4",
        productName: "Ergonomic Office Chair",
        productSku: "CHAIR-ERG-001",
        requestedQuantity: 20,
        sentQuantity: 20,
        receivedQuantity: 0,
      },
    ],
  },
  {
    id: "trf-2",
    transferNumber: "TRF-20260303-0091",
    sourceWarehouseId: "wh-1",
    sourceWarehouseName: "Main Warehouse",
    destinationWarehouseId: "wh-2",
    destinationWarehouseName: "North Branch Store",
    status: "PENDING_APPROVAL",
    requestedById: "usr-sm-1",
    requestedByName: "Marcus Sterling",
    sentById: null,
    sentByName: null,
    receivedById: null,
    receivedByName: null,
    sentDate: null,
    receivedDate: null,
    notes: "Rebalancing stock between branches.",
    createdAt: "2026-03-03T16:00:00Z",
    items: [
      {
        id: "ti-2",
        stockTransferId: "trf-2",
        productId: "prod-3",
        productName: "Mechanical Keyboard TKL",
        productSku: "KB-MECH-001",
        requestedQuantity: 15,
        sentQuantity: 0,
        receivedQuantity: 0,
      },
    ],
  },
];

export const INITIAL_ALERTS: LowStockAlertDTO[] = [
  {
    id: "alt-1",
    productId: "prod-2",
    productName: "Logitech Wireless Mouse",
    productSku: "LOG-MOUSE-001",
    barcode: "890123456702",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    currentQuantity: 20,
    minStockLevel: 40,
    shortageQuantity: 20,
    status: "NEW",
    createdAt: "2026-03-02T15:21:00Z",
  },
  {
    id: "alt-2",
    productId: "prod-5",
    productName: "A4 Printer Paper 500 Sheets",
    productSku: "PAPER-A4-001",
    barcode: "890123456705",
    warehouseId: "wh-1",
    warehouseName: "Main Warehouse",
    currentQuantity: 0,
    minStockLevel: 100,
    shortageQuantity: 100,
    status: "NEW",
    createdAt: "2026-03-03T09:01:00Z",
  },
];

export const INITIAL_NOTIFICATIONS: NotificationDTO[] = [
  {
    id: "notif-1",
    title: "Critical Stock Out",
    message: "A4 Printer Paper (PAPER-A4-001) is out of stock in Main Warehouse.",
    type: "OUT_OF_STOCK",
    link: "/low-stock",
    read: false,
    createdAt: "2026-03-03T09:02:00Z",
  },
  {
    id: "notif-2",
    title: "Stock Transfer In Transit",
    message: "Transfer TRF-20260302-0044 (20 helmets) dispatched to Overflow Storage.",
    type: "STOCK_TRANSFER",
    link: "/stock-transfers",
    read: false,
    createdAt: "2026-03-02T11:05:00Z",
  },
  {
    id: "notif-3",
    title: "New Purchase Order Submitted",
    message: "PO-20260302-5102 for $4,200.00 submitted for approval.",
    type: "PURCHASE_ORDER",
    link: "/purchase-orders",
    read: true,
    createdAt: "2026-03-02T10:02:00Z",
  },
];

export const INITIAL_FORECASTS: ForecastDTO[] = [
  {
    id: "fc-1",
    productId: "prod-1",
    productName: "Dell Laptop 15-inch",
    productSku: "DELL-LAPTOP-001",
    calculatedAt: "2026-03-03T00:00:00Z",
    dailyAvgSales: 4.8,
    predictedDemand7d: 34,
    predictedDemand30d: 144,
    currentStock: 140,
    estimatedDaysRemaining: 29,
    recommendedReorderQty: 50,
    historicalSalesTrend: [
      { date: "Feb 24", quantity: 5 },
      { date: "Feb 25", quantity: 4 },
      { date: "Feb 26", quantity: 6 },
      { date: "Feb 27", quantity: 3 },
      { date: "Feb 28", quantity: 7 },
      { date: "Mar 01", quantity: 10 },
      { date: "Mar 02", quantity: 8 },
    ],
    projectedSalesTrend: [
      { date: "Mar 04", quantity: 5 },
      { date: "Mar 05", quantity: 5 },
      { date: "Mar 06", quantity: 6 },
      { date: "Mar 07", quantity: 4 },
      { date: "Mar 08", quantity: 5 },
      { date: "Mar 09", quantity: 5 },
      { date: "Mar 10", quantity: 6 },
    ],
    notes: "Steady high demand driven by enterprise OEM contracts.",
  },
  {
    id: "fc-2",
    productId: "prod-2",
    productName: "Logitech Wireless Mouse",
    productSku: "LOG-MOUSE-001",
    calculatedAt: "2026-03-03T00:00:00Z",
    dailyAvgSales: 3.5,
    predictedDemand7d: 25,
    predictedDemand30d: 105,
    currentStock: 35,
    estimatedDaysRemaining: 10,
    recommendedReorderQty: 100,
    historicalSalesTrend: [
      { date: "Feb 24", quantity: 3 },
      { date: "Feb 25", quantity: 2 },
      { date: "Feb 26", quantity: 5 },
      { date: "Feb 27", quantity: 4 },
      { date: "Feb 28", quantity: 4 },
      { date: "Mar 01", quantity: 3 },
      { date: "Mar 02", quantity: 4 },
    ],
    projectedSalesTrend: [
      { date: "Mar 04", quantity: 4 },
      { date: "Mar 05", quantity: 3 },
      { date: "Mar 06", quantity: 4 },
      { date: "Mar 07", quantity: 3 },
      { date: "Mar 08", quantity: 4 },
      { date: "Mar 09", quantity: 4 },
      { date: "Mar 10", quantity: 3 },
    ],
    notes: "Urgent reorder required within 48 hours to avoid total stockout.",
  },
  {
    id: "fc-3",
    productId: "prod-3",
    productName: "Mechanical Keyboard TKL",
    productSku: "KB-MECH-001",
    calculatedAt: "2026-03-03T00:00:00Z",
    dailyAvgSales: 2.9,
    predictedDemand7d: 20,
    predictedDemand30d: 87,
    currentStock: 95,
    estimatedDaysRemaining: 32,
    recommendedReorderQty: 40,
    historicalSalesTrend: [
      { date: "Feb 24", quantity: 2 },
      { date: "Feb 25", quantity: 3 },
      { date: "Feb 26", quantity: 1 },
      { date: "Feb 27", quantity: 4 },
      { date: "Feb 28", quantity: 3 },
      { date: "Mar 01", quantity: 10 },
      { date: "Mar 02", quantity: 2 },
    ],
    projectedSalesTrend: [
      { date: "Mar 04", quantity: 3 },
      { date: "Mar 05", quantity: 3 },
      { date: "Mar 06", quantity: 3 },
      { date: "Mar 07", quantity: 2 },
      { date: "Mar 08", quantity: 3 },
      { date: "Mar 09", quantity: 3 },
      { date: "Mar 10", quantity: 3 },
    ],
    notes: "Comfortable stock coverage for the next 30 days.",
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogDTO[] = [
  {
    id: "aud-1",
    userId: "usr-wm-1",
    userName: "Elena Rostova",
    action: "RECEIVE_PURCHASE_ORDER",
    resourceType: "PURCHASE_ORDER",
    resourceId: "po-1",
    description: "Received 50 units of Dell Laptop 15-inch into Main Warehouse.",
    createdAt: "2026-03-01T10:16:00Z",
  },
  {
    id: "aud-2",
    userId: "usr-sm-1",
    userName: "Marcus Sterling",
    action: "CONFIRM_SALES_ORDER",
    resourceType: "SALES_ORDER",
    resourceId: "so-1",
    description: "Confirmed Sales Order SO-20260301-8841 for Star Electronics Shop.",
    createdAt: "2026-03-01T13:02:00Z",
  },
  {
    id: "aud-3",
    userId: "usr-wm-1",
    userName: "Elena Rostova",
    action: "DISPATCH_STOCK_TRANSFER",
    resourceType: "STOCK_TRANSFER",
    resourceId: "trf-1",
    description: "Dispatched 20 Ergonomic Office Chairs from Main Warehouse to Overflow Storage.",
    createdAt: "2026-03-02T11:01:00Z",
  },
  {
    id: "aud-4",
    userId: "usr-wm-1",
    userName: "Elena Rostova",
    action: "ADJUST_INVENTORY",
    resourceType: "PRODUCT",
    resourceId: "prod-2",
    description: "Manual stock reduction by -2 units due to shelf damage.",
    createdAt: "2026-03-02T15:20:00Z",
  },
];
